spring.application.name=TestApplication

# --- BAZA DANYCH ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/Magisterka}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# --- REDIS (Cache Rozproszony) ---
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=6379

# --- LOGI ---
logging.level.org.hibernate.SQL=ERROR
logging.level.org.springframework.web=INFO